# Generated by Django 3.1.7 on 2021-04-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0002_auto_20210402_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='desc',
            new_name='Desc',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='name',
            new_name='Username',
        ),
    ]
