# Generated by Django 3.1.7 on 2021-04-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0005_auto_20210402_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Desc',
            field=models.TextField(null=True),
        ),
    ]
